### ISSUE TITLE
Calibrate one science run using comp mags from another.

### ISSUE THREAD

**Issue by StuartLittlefair** [Alex-J-Brown/cam-calib#2]
Hi Alex,

For precise flux calibration, both the standard star and the comparison star log files should be reduced with a fixed, large, aperture. This is to minimise the effects of aperture losses. 

Suppose you use a small aperture for both, and the standard star has significantly poorer IQ: in this case the aperture losses are very different between the two runs. This issue is magnified if you want to use optimal extraction.

So what I'd like to be able to do is something like this:

```python
# standard star, reduced with large, fixed aperture
obs.add_observation(name='GD71', logfiles=['run017_fcal.log'], obs_type='std', cal_mags=GD71_mags)
obs.get_zeropoint()

# science data, reduced with same large aperture
obs.add_observation(name='1716bx J160335.93+215032.3', logfiles=['run034_fcal.log'], obs_type='fcal')
obs.calc_comparison_mags()  # sets comparison star mags from 'fcal' observation

# science data, reduced with "best" aperture
obs.add_observation(name='1716bx J160335.93+215032.3', logfiles=['run034.log'], obs_type='science')
obs.calibrate_science('1716bx J160335.93+215032.3')  # uses comp mags from the calculation above
```

**Comment by Alex-J-Brown** [comment]
I've attempted to write a fix for this (which I think should also solve issue #1?)
Give me a shout if you have problems

**Comment by StuartLittlefair** [comment]
lovely. works perfectly now I did it properly!

**Comment by Alex-J-Brown** [comment]
Does the flux calibration match what you get doing it by hand now then?

**Comment by StuartLittlefair** [comment]
Yep, spot on

**Comment by Alex-J-Brown** [comment]
Ok great, I'll close this and issue #1
