### ISSUE TITLE
cam_cal assumes a directory structure when finding hcm file

### ISSUE THREAD

**Issue by StuartLittlefair** [Alex-J-Brown/cam-calib#5]
In `logfile` you set `self.run` from the "run" entry in the log file. 

But this is the location of the raw data, and quite often the raw data will be on a different path in the filesystem whereas the .hcm file is more likely to be where the .red, .log files are. 

For example, I often reduce data with the `run` entry /astronas1/vsd/.....

**Comment by Alex-J-Brown** [comment]
I've added ``os.path.basename`` around the ``run`` entry to remove all the extra path. Hopefully that'll fix what you're talking about?

**Comment by StuartLittlefair** [comment]
yep - that will do it!
